# Generated by Django 5.1.1 on 2024-09-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
