# Generated by Django 5.1.1 on 2024-09-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrador'), (2, 'Bibliotecario'), (3, 'Asistente'), (4, 'Cliente')], default=4),
        ),
    ]
